# Generated by Django 4.2 on 2023-05-03 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0005_livros_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='quantidade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
