# Generated by Django 4.2 on 2023-05-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0011_emprestimo_nome_emprestado_anonimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='nome_emprestado_anonimo',
        ),
    ]
