# Generated by Django 4.2 on 2023-05-25 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('livro', '0013_emprestimo_nome_emprestado_anonimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='registro_usuario_de_livro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='emprestimo_usuario', to='usuarios.usuario'),
        ),
    ]
