# Generated by Django 4.2 on 2023-05-25 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0014_emprestimo_registro_usuario_de_livro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='registro_usuario_de_livro',
            new_name='nome_emprestado_usuario',
        ),
    ]
