# Generated by Django 4.2 on 2023-05-26 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0015_rename_registro_usuario_de_livro_emprestimo_nome_emprestado_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='usuario',
        ),
    ]
