# Generated by Django 4.2 on 2023-05-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0016_remove_emprestimo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='data_emprestado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
