# Generated by Django 4.2 on 2023-05-27 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0017_emprestimo_data_emprestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='livros',
            name='data_lancamento',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
